/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Query */
        post: operations["agent_query_agent_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_artifacts_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Return the canonical artifact for `artifact_id`.
         */
        get: operations["get_artifact_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/data-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Profile
         * @description Return the data profile section for `artifact_id`.
         *
         *     Returns column distributions, missingness rates, and pairwise Pearson
         *     correlations from the training table. When no training table was provided
         *     at extraction time, returns HTTP 200 with a detail message.
         */
        get: operations["get_data_profile_artifacts__artifact_id__data_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Enrich
         * @description Add a data profile section to an existing artifact.
         *
         *     SHAP and evaluation enrichment require re-ingesting the model file via
         *     POST /artifacts/ingest — the API layer cannot import LightGBM (invariant #2).
         */
        patch: operations["enrich_artifacts__artifact_id__enrich_patch"];
        trace?: never;
    };
    "/artifacts/{artifact_id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evaluation
         * @description Return the evaluation section for `artifact_id`.
         *
         *     Returns objective-aware evaluation metrics (ROC/confusion matrix for
         *     binary, NxN confusion + per-class metrics for multiclass, residuals
         *     for regression, nDCG@k for ranking). When evaluation was not computed,
         *     returns HTTP 200 with a detail message.
         */
        get: operations["get_evaluation_artifacts__artifact_id__evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/explanations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Explanations
         * @description Return the explanations section for `artifact_id`.
         *
         *     Returns the SHAP values, decision paths, and partial dependence profiles
         *     stored at extraction time. When explanations were not computed, returns
         *     HTTP 200 with a detail message (not 404 — the artifact exists).
         */
        get: operations["get_explanations_artifacts__artifact_id__explanations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/importance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Importance
         * @description Return importance scores for the requested type.
         *
         *     - gain / split: always available (computed at extraction time).
         *     - permutation: available only when evaluation samples were provided
         *       at extraction time; returns HTTP 200 with empty features list and a
         *       detail message when absent.
         */
        get: operations["get_importance_artifacts__artifact_id__importance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — does not check storage or downstream deps.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_models__model_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_models__model_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentQueryRequest */
        AgentQueryRequest: {
            /** Artifact Id */
            artifact_id: string;
            /** Question */
            question: string;
        };
        /** AgentQueryResponse */
        AgentQueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
        };
        /**
         * BinaryEval
         * @description Binary classification evaluation metrics.
         */
        BinaryEval: {
            /** Auc */
            auc: number;
            /** Confusion Matrix */
            confusion_matrix: components["schemas"]["ConfusionCell"][];
            /** F1 */
            f1: number;
            /**
             * Objective
             * @constant
             */
            objective: "binary";
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** Roc Curve */
            roc_curve: components["schemas"]["ROCPoint"][];
            /** Threshold */
            threshold: number;
        };
        /** Body_enrich_artifacts__artifact_id__enrich_patch */
        Body_enrich_artifacts__artifact_id__enrich_patch: {
            /** Training Table */
            training_table?: string | null;
        };
        /** Body_ingest_artifacts_ingest_post */
        Body_ingest_artifacts_ingest_post: {
            /** Eval Labels */
            eval_labels?: string | null;
            /** Eval Samples */
            eval_samples?: string | null;
            /** Labels */
            labels?: string | null;
            /**
             * Model
             * @description LightGBM .txt model file
             */
            model: string;
            /**
             * Model Name
             * @description Logical model name, e.g. 'loan_default_classifier'
             */
            model_name: string;
            /** Notes */
            notes?: string | null;
            /** Samples */
            samples?: string | null;
            /** Training Table */
            training_table?: string | null;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Count */
            count: number;
            /** Value */
            value: string;
        };
        /**
         * CerebroArtifact
         * @description The whole canonical artifact — the contract every layer agrees on.
         */
        CerebroArtifact: {
            data_profile?: components["schemas"]["DataProfile"] | null;
            /** Evaluation */
            evaluation?: components["schemas"]["BinaryEval"] | components["schemas"]["MulticlassEval"] | components["schemas"]["RegressionEval"] | components["schemas"]["RankingEval"] | null;
            explanations?: components["schemas"]["Explanations"] | null;
            importance: components["schemas"]["Importance"];
            model: components["schemas"]["Model"];
            /** Rank Metadata */
            rank_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            source: components["schemas"]["Source"];
            /** Trees */
            trees: components["schemas"]["Tree"][];
        };
        /**
         * ColumnProfile
         * @description Per-column statistical profile.
         */
        ColumnProfile: {
            /** Dtype */
            dtype: string;
            /** Histogram */
            histogram?: components["schemas"]["HistogramBin"][] | null;
            /** Is Categorical */
            is_categorical: boolean;
            /** Is Numeric */
            is_numeric: boolean;
            /** Max */
            max?: number | null;
            /** Mean */
            mean?: number | null;
            /** Min */
            min?: number | null;
            /** Missingness */
            missingness: number;
            /** Name */
            name: string;
            /** Null Count */
            null_count: number;
            /** Std */
            std?: number | null;
            /** Top Categories */
            top_categories?: components["schemas"]["CategoryCount"][] | null;
            /** Total Rows */
            total_rows: number;
        };
        /** ConfusionCell */
        ConfusionCell: {
            /** Actual */
            actual: number;
            /** Count */
            count: number;
            /** Predicted */
            predicted: number;
        };
        /** CorrelationCell */
        CorrelationCell: {
            /** Feature A */
            feature_a: string;
            /** Feature B */
            feature_b: string;
            /** Pearson */
            pearson: number;
        };
        /**
         * DataProfile
         * @description Statistical summary of the training table.
         */
        DataProfile: {
            /** Column Count */
            column_count: number;
            /** Columns */
            columns: components["schemas"]["ColumnProfile"][];
            /** Correlations */
            correlations: components["schemas"]["CorrelationCell"][];
            /** Row Count */
            row_count: number;
        };
        /**
         * DecisionPath
         * @description Traced path through a single tree for one sample.
         */
        DecisionPath: {
            /** Leaf Value */
            leaf_value: number;
            /** Steps */
            steps: components["schemas"]["DecisionStep"][];
            /** Tree Index */
            tree_index: number;
        };
        /**
         * DecisionStep
         * @description One split node on the path from root to leaf.
         */
        DecisionStep: {
            /** Decision Type */
            decision_type: string;
            /** Feature Index */
            feature_index: number;
            /** Feature Name */
            feature_name: string;
            /** Node Id */
            node_id: number;
            /** Sample Value */
            sample_value: number;
            /** Threshold */
            threshold: number | null;
            /** Went Left */
            went_left: boolean;
        };
        /** EnrichResponse */
        EnrichResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Enriched At */
            enriched_at: string;
            /** Sections Added */
            sections_added: string[];
        };
        /**
         * Explanations
         * @description Full explanations bundle stored in the artifact.
         */
        Explanations: {
            /** Decision Paths */
            decision_paths?: components["schemas"]["DecisionPath"][][] | null;
            /** Partial Dependence */
            partial_dependence?: components["schemas"]["PDPFeature"][] | null;
            shap?: components["schemas"]["ShapResult"] | null;
        };
        /**
         * FeatureSchema
         * @description The features the model sees, in input order.
         *
         *     `monotone_constraints` has the same length as `names`. A value of 0 means
         *     no monotonicity is enforced; +1 / -1 enforce increasing / decreasing
         *     relationships between the feature and the prediction.
         */
        FeatureSchema: {
            /** Categorical Indices */
            categorical_indices: number[];
            /** Monotone Constraints */
            monotone_constraints: number[];
            /** Names */
            names: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthBody
         * @description Response shape for `GET /health`.
         */
        HealthBody: {
            /**
             * Agent Status
             * @enum {string}
             */
            agent_status: "available" | "unconfigured" | "unreachable";
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** HistogramBin */
        HistogramBin: {
            /** Count */
            count: number;
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
        };
        /**
         * Importance
         * @description Feature importance scores keyed by feature name.
         */
        Importance: {
            /** Divergence Warnings */
            divergence_warnings?: {
                [key: string]: string | number;
            }[] | null;
            /** Gain */
            gain: {
                [key: string]: number;
            };
            /** Permutation */
            permutation?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
            /** Split */
            split: {
                [key: string]: number;
            };
        };
        /** IngestResponse */
        IngestResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            sections: components["schemas"]["SectionStatus"];
            /** Version */
            version: number;
        };
        /** IntervalPoint */
        IntervalPoint: {
            /** Lower */
            lower: number;
            /** Predicted */
            predicted: number;
            /** Upper */
            upper: number;
        };
        /**
         * Model
         * @description Booster-level metadata: objective, parameters, feature shape.
         *
         *     `params` is typed as `dict[str, Any]` because LightGBM stores a mix of
         *     scalars, lists, and nested dicts; tightening this would require enumerating
         *     every LightGBM parameter and would still need updates when LightGBM adds
         *     parameters. The booster contract is what enforces shape — the extractor
         *     forwards what LightGBM gives us.
         */
        Model: {
            feature_schema: components["schemas"]["FeatureSchema"];
            /** Num Class */
            num_class: number;
            /** Num Iteration */
            num_iteration: number;
            /**
             * Objective
             * @enum {string}
             */
            objective: "binary" | "multiclass" | "regression" | "lambdarank" | "multi_output";
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelDetail
         * @description Detail page data — full version history, newest first.
         */
        ModelDetail: {
            /** Created At */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Versions */
            versions: components["schemas"]["VersionSummary"][];
        };
        /**
         * ModelSummary
         * @description Card data for the registry home view.
         */
        ModelSummary: {
            /** Created At */
            created_at: string;
            /** Description */
            description: string | null;
            /** Framework */
            framework: string;
            /** Id */
            id: string;
            /** Latest Version */
            latest_version: number;
            /** Latest Version Date */
            latest_version_date: string;
            /** Name */
            name: string;
            /** Objective */
            objective: string;
            section_status: components["schemas"]["SectionStatus"];
        };
        /**
         * MulticlassEval
         * @description Multiclass classification evaluation metrics.
         */
        MulticlassEval: {
            /** Accuracy */
            accuracy: number;
            /** Confusion Matrix */
            confusion_matrix: components["schemas"]["ConfusionCell"][];
            /** Macro F1 */
            macro_f1: number;
            /**
             * Objective
             * @constant
             */
            objective: "multiclass";
            /** Per Class */
            per_class: components["schemas"]["PerClassMetrics"][];
        };
        /** NDCGAtK */
        NDCGAtK: {
            /** K */
            k: number;
            /** Value */
            value: number;
        };
        /**
         * PDPFeature
         * @description Partial dependence profile for one feature.
         */
        PDPFeature: {
            /** Feature */
            feature: string;
            /** Feature Index */
            feature_index: number;
            /** Grid */
            grid: number[];
            /** Is Categorical */
            is_categorical: boolean;
            /** Values */
            values: number[];
        };
        /** PerClassMetrics */
        PerClassMetrics: {
            /** Class Index */
            class_index: number;
            /** F1 */
            f1: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** Support */
            support: number;
        };
        /** ROCPoint */
        ROCPoint: {
            /** Fpr */
            fpr: number;
            /** Threshold */
            threshold: number;
            /** Tpr */
            tpr: number;
        };
        /**
         * RankingEval
         * @description Ranking (lambdarank) evaluation metrics.
         */
        RankingEval: {
            /** Mean Average Precision */
            mean_average_precision: number;
            /** Ndcg At K */
            ndcg_at_k: components["schemas"]["NDCGAtK"][];
            /**
             * Objective
             * @constant
             */
            objective: "lambdarank";
            /** Per Query Ndcg */
            per_query_ndcg: number[];
        };
        /**
         * RegressionEval
         * @description Regression evaluation metrics.
         */
        RegressionEval: {
            /** Interval Band */
            interval_band: components["schemas"]["IntervalPoint"][];
            /** Mae */
            mae: number;
            /**
             * Objective
             * @constant
             */
            objective: "regression";
            /** R2 */
            r2: number;
            /** Residuals Histogram */
            residuals_histogram: components["schemas"]["HistogramBin"][];
            /** Rmse */
            rmse: number;
            /** Scatter */
            scatter: components["schemas"]["ScatterPoint"][];
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
        };
        /** SectionStatus */
        SectionStatus: {
            /** Data Profile */
            data_profile: boolean;
            /** Evaluation */
            evaluation: boolean;
            /** Importance */
            importance: boolean;
            /** Shap */
            shap: boolean;
            /** Trees */
            trees: boolean;
        };
        /**
         * ShapResult
         * @description SHAP values for a set of samples.
         *
         *     `shap_values` has shape (n_samples, n_features) for binary and regression
         *     models. For multiclass it has shape (n_samples, n_classes, n_features),
         *     stored as a nested list.
         *     `expected_value` is a scalar for binary/regression; a list of per-class
         *     base values for multiclass.
         */
        ShapResult: {
            /** Background Sample Count */
            background_sample_count: number;
            /** Expected Value */
            expected_value: number | number[];
            /** Feature Names */
            feature_names: string[];
            /** Sample Count */
            sample_count: number;
            /** Shap Values */
            shap_values: number[][] | number[][][];
        };
        /**
         * Source
         * @description Where this artifact came from and when.
         */
        Source: {
            /** Extracted At */
            extracted_at: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * Framework
             * @constant
             */
            framework: "lightgbm";
            /** Framework Version */
            framework_version: string;
        };
        /**
         * Tree
         * @description One tree in the ensemble.
         *
         *     `class_index` is null for binary boosters; per-class trees in multiclass
         *     boosters set it to the class they predict (a future schema bump).
         */
        Tree: {
            /** Class Index */
            class_index?: number | null;
            /** Index */
            index: number;
            /** Num Leaves */
            num_leaves: number;
            root: components["schemas"]["TreeNode"];
        };
        /**
         * TreeNode
         * @description One node in a decision tree (recursive).
         */
        TreeNode: {
            /** Decision Type */
            decision_type?: ("<=" | "==") | null;
            /** Id */
            id: number;
            /** Leaf Value */
            leaf_value?: number | null;
            left?: components["schemas"]["TreeNode"] | null;
            right?: components["schemas"]["TreeNode"] | null;
            /** Split Feature */
            split_feature?: number | null;
            /** Threshold */
            threshold?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionSummary */
        VersionSummary: {
            /** Artifact Id */
            artifact_id: string;
            /** Created At */
            created_at: string;
            /** Notes */
            notes: string | null;
            section_status: components["schemas"]["SectionStatus"];
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agent_query_agent_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_artifacts_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_artifacts_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CerebroArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_profile_artifacts__artifact_id__data_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_artifacts__artifact_id__enrich_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enrich_artifacts__artifact_id__enrich_patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_artifacts__artifact_id__evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explanations_artifacts__artifact_id__explanations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_importance_artifacts__artifact_id__importance_get: {
        parameters: {
            query: {
                /** @description Importance type: gain, split, or permutation */
                type: string;
            };
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthBody"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: {
                framework?: string | null;
                objective?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_models__model_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_models__model_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
